spring:
  r2dbc:
    url: r2dbc:postgres://127.0.0.1:5432/cabinet
    username: postgres
    password: ${PASSWORD}
    pool:
      enabled: true
      initial-size: 50
      max-size: 100
  redis:
    host: localhost
    port: 6379
server:
  port: 8082
token:
  secret: jiU*7?KOji9834
  header: Authorization
  expireTime: 30
#logging:
#  level:
#    root: debug
#debug: true
